// Precompute the 169x169 heads-up all-in preflop equity matrix.
//
// This is the one thing that is too expensive to do in a browser tab, so it
// runs offline and ships as a ~40 KB table. Everything downstream — the Nash
// push/fold solver, "top 15%" range expansion, preflop hand ranking — reads it.
//
// Method: for each unordered pair of the 169 starting-hand classes, enumerate
// every disjoint combo pairing (card removal is exact) and run a stratified
// Monte Carlo board sample inside each. Equity is win + tie/2.
//
//   node tools/build-preflop.mjs [--samples 120000] [--threads 4]

import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import os from 'node:os';
import { combosOfClass, classLabel } from '../engine/cards.js';
import { evaluate } from '../engine/evaluator.js';
import { makeRng, partialShuffle } from '../engine/rng.js';

const CLASSES = 169;
const PAIRS = [];
for (let i = 0; i < CLASSES; i++) for (let j = i + 1; j < CLASSES; j++) PAIRS.push([i, j]);

const COMBOS = Array.from({ length: CLASSES }, (_, i) => combosOfClass(i));

/** Equity of class `i` against class `j`, averaged over every disjoint combo pairing. */
function classEquity(i, j, samples, rng) {
  const a = COMBOS[i];
  const b = COMBOS[j];

  const pairs = [];
  for (const ca of a) for (const cb of b) {
    if (ca[0] === cb[0] || ca[0] === cb[1] || ca[1] === cb[0] || ca[1] === cb[1]) continue;
    pairs.push([ca, cb]);
  }
  if (pairs.length === 0) return 0.5; // cannot happen for i !== j, but stay total

  const perPair = Math.max(1, Math.round(samples / pairs.length));
  const hero = new Int32Array(7);
  const villain = new Int32Array(7);
  const avail = new Int8Array(48);
  const blocked = new Uint8Array(52);

  let total = 0;
  let sum = 0;

  for (const [ca, cb] of pairs) {
    blocked.fill(0);
    blocked[ca[0]] = 1; blocked[ca[1]] = 1; blocked[cb[0]] = 1; blocked[cb[1]] = 1;
    let n = 0;
    for (let c = 0; c < 52; c++) if (!blocked[c]) avail[n++] = c;

    hero[0] = ca[0]; hero[1] = ca[1];
    villain[0] = cb[0]; villain[1] = cb[1];

    for (let s = 0; s < perPair; s++) {
      partialShuffle(avail, 5, rng);
      for (let k = 0; k < 5; k++) { hero[2 + k] = avail[k]; villain[2 + k] = avail[k]; }
      const hs = evaluate(hero, 7);
      const vs = evaluate(villain, 7);
      sum += hs > vs ? 1 : hs === vs ? 0.5 : 0;
      total++;
    }
  }
  return sum / total;
}

if (!isMainThread) {
  const { from, to, samples, seed } = workerData;
  const rng = makeRng(seed);
  const out = new Float64Array(to - from);
  for (let k = from; k < to; k++) {
    const [i, j] = PAIRS[k];
    out[k - from] = classEquity(i, j, samples, rng);
    if ((k - from) % 200 === 0) parentPort.postMessage({ progress: k - from });
  }
  parentPort.postMessage({ done: true, from, to, values: out }, [out.buffer]);
} else {
  const argv = process.argv.slice(2);
  const arg = (name, fallback) => {
    const i = argv.indexOf(`--${name}`);
    return i >= 0 ? Number(argv[i + 1]) : fallback;
  };
  const samples = arg('samples', 120_000);
  const threads = Math.max(1, Math.min(arg('threads', os.cpus().length), 16));

  const started = Date.now();
  console.log(`solving ${PAIRS.length.toLocaleString()} class matchups ` +
    `x ~${samples.toLocaleString()} boards on ${threads} threads`);

  const eq = new Float64Array(PAIRS.length);
  const chunk = Math.ceil(PAIRS.length / threads);
  const progress = new Array(threads).fill(0);
  const self = fileURLToPath(import.meta.url);

  await Promise.all(Array.from({ length: threads }, (_, t) => new Promise((resolve, reject) => {
    const from = t * chunk;
    const to = Math.min(PAIRS.length, from + chunk);
    if (from >= to) return resolve();
    const w = new Worker(self, { workerData: { from, to, samples, seed: 1000 + t * 7919 } });
    w.on('message', (m) => {
      if (m.done) {
        eq.set(m.values, m.from);
        resolve();
      } else {
        progress[t] = m.progress;
        const total = progress.reduce((a, b) => a + b, 0);
        const pct = ((total / PAIRS.length) * 100).toFixed(1);
        const elapsed = (Date.now() - started) / 1000;
        process.stdout.write(`\r  ${pct}%  ${elapsed.toFixed(0)}s elapsed   `);
      }
    });
    w.on('error', reject);
  })));

  process.stdout.write('\n');

  // Quantise to uint16. 1/65535 ~ 0.0015% of equity, far below sampling error.
  const quant = new Uint16Array(PAIRS.length);
  for (let k = 0; k < PAIRS.length; k++) {
    quant[k] = Math.max(0, Math.min(65535, Math.round(eq[k] * 65535)));
  }
  const b64 = Buffer.from(quant.buffer, quant.byteOffset, quant.byteLength).toString('base64');

  const wrapped = b64.replace(/(.{100})/g, '$1\n');
  const file = `// GENERATED by tools/build-preflop.mjs — do not edit by hand.
//
// Heads-up all-in preflop equity for every unordered pair of the 169 starting
// hand classes, averaged over all disjoint combo pairings (exact card removal)
// with ~${samples.toLocaleString()} sampled boards per matchup.
// Sampling error is roughly +/-${(50 / Math.sqrt(samples)).toFixed(2)}% per entry.
//
// Stored as the strict upper triangle, uint16 little-endian, base64.
// Entry (i, j) with i < j holds P(class i beats class j); the lower triangle is
// its complement and the diagonal is exactly 0.5 by symmetry.

export const PREFLOP_SAMPLES = ${samples};

const PACKED = '\\
${wrapped.split('\n').join('\\\n')}';

${'/'}** Upper-triangle index for i < j over 169 classes. *${'/'}
export function triIndex(i, j) {
  return (i * (337 - i)) / 2 + (j - i - 1);
}

function decode() {
  const bin = typeof atob === 'function'
    ? atob(PACKED)
    : Buffer.from(PACKED, 'base64').toString('binary');
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new Uint16Array(bytes.buffer, bytes.byteOffset, bytes.byteLength >> 1);
}

const TRI = decode();

${'/'}** Full 169x169 equity matrix: EQUITY[i * 169 + j] = equity of class i vs class j. *${'/'}
export const EQUITY = (() => {
  const m = new Float32Array(169 * 169);
  for (let i = 0; i < 169; i++) {
    m[i * 169 + i] = 0.5;
    for (let j = i + 1; j < 169; j++) {
      const e = TRI[triIndex(i, j)] / 65535;
      m[i * 169 + j] = e;
      m[j * 169 + i] = 1 - e;
    }
  }
  return m;
})();
`;

  writeFileSync(new URL('../data/preflop-equity.js', import.meta.url), file);
  console.log(`wrote data/preflop-equity.js (${(file.length / 1024).toFixed(0)} KB) ` +
    `in ${((Date.now() - started) / 1000).toFixed(0)}s`);

  // Eyeball a few well-known matchups so a bad build is obvious immediately.
  const idx = (i, j) => (i * (337 - i)) / 2 + (j - i - 1);
  const byLabel = new Map();
  for (let i = 0; i < CLASSES; i++) byLabel.set(classLabel(i), i);
  const show = (x, y) => {
    const i = byLabel.get(x), j = byLabel.get(y);
    const e = i < j ? eq[idx(i, j)] : 1 - eq[idx(j, i)];
    console.log(`  ${x.padEnd(4)} vs ${y.padEnd(4)} ${(e * 100).toFixed(2)}%`);
  };
  show('AA', 'KK'); show('AA', '72o'); show('AKs', 'QQ');
  show('JJ', 'AKo'); show('QQ', 'AKs'); show('54s', 'AKo');
}
